### ISSUE TITLE
Bro can't even run infooze and can't remove

### ISSUE THREAD

**Issue by SkyCreedPH** [devXprite/infoooze#25]
### Describe the bug

How do i fix this issue on kali linux

### Steps to reproduce

1. First i run the commands i do all
2. Then after that 
3. And then it doesn't work lol

**Comment by devXprite** [comment]
Hii Bro,

From the screenshot you shared, it looks like the tool was not installed correctly. Could you please let me know which installation command you used? This will help me better understand the issue you're experiencing and suggest a solution.

In the meantime, as an alternative, you could try installing the tool using the following method:

```
git clone https://github.com/devXprite/infoooze
cd infoooze
npm install
node .
```

Please let me know if this helps.

**Comment by SkyCreedPH** [comment]
![Screenshot_2022-12-22-02-58-17-25_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/92684213/208982636-ec33798a-62ae-4f53-b3f6-3df039e4ede3.jpg)


what does it mean

**Comment by devXprite** [comment]
> ![Screenshot_2022-12-22-02-58-17-25_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/92684213/208982636-ec33798a-62ae-4f53-b3f6-3df039e4ede3.jpg)
> 
> what does it mean

It looks like the issue you're experiencing is related to npm, rather than the tool itself.

I'm sorry that I don't have a definite solution for you, but I wanted to suggest a couple of things you could try that might help.

You can try following command in the project directory:
```
npm install -g npm
rm package-lock.json
npm cache clean --force
npm cache verify
npm install
```

I hope one of these suggestions helps! If neither of these solutions resolves the issue, you may need to try reinstalling Node.js and npm.

**Comment by devXprite** [comment]
> ![Screenshot_2022-12-22-02-58-17-25_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/92684213/208982636-ec33798a-62ae-4f53-b3f6-3df039e4ede3.jpg)
> 
> what does it mean

It looks like the issue you're experiencing is related to npm, rather than the tool itself.

I'm sorry that I don't have a definite solution for you, but I wanted to suggest a couple of things you could try that might help.

You can try following command in the project directory:
```
npm install -g npm
rm package-lock.json
npm cache clean --force
npm cache verify
npm install
```

I hope one of these suggestions helps! If neither of these solutions resolves the issue, you may need to try reinstalling Node.js and npm.

**Comment by SkyCreedPH** [comment]
how do i reinstall node.js im new kali hunter user sorry that im not good at this i just want to learn

**Comment by SkyCreedPH** [comment]
![Screenshot_2022-12-22-15-33-56-22_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/92684213/209081575-0d2e3406-a2fc-48ae-a224-11b4302cb48e.jpg)

what does it mean

**Comment by SkyCreedPH** [comment]
![Screenshot_2022-12-22-15-35-48-10_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/92684213/209081780-63204679-41d9-4cba-81ed-ab2a72430a74.jpg)



How do I reinstall node.js

**Comment by devXprite** [comment]
> how do i reinstall node.js im new kali hunter user sorry that im not good at this i just want to learn Edit: this command doesn't work "rm package-lock.json" said "rm: cannot remove 'package-lock.json': No such file or directory"



Actually I assumed that you were using **Termux** so just ignore the previous commands that I sent.

Since you're using Kali NetHunter, you will need to use the sudo command to install the tool globally:
```
sudo npm install infoooze -g
```

Before installing the tool, it's also a good idea to update the npm package list using: `sudo npm update`

If you have still error, just send me your node and npm version with error screenshot. I'm always happy to help. 😀

**Comment by SkyCreedPH** [comment]
Thank you bro

**Comment by SkyCreedPH** [comment]
![Uploading Screenshot_2022-12-22-15-33-56-22_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by devXprite** [comment]
> 

Hii bro, screenshot is not displaying properly.
Could you please try re-uploading the screenshot?

**Comment by SkyCreedPH** [comment]
Is there a social media platform I can add you to?

**Comment by devXprite** [comment]
> Is there a social media platform I can add you to?

Sure you can DM me on [Twitter](twitter.com/devxprite)  or [Instagram](instagram.com/devxprite)
